### ISSUE TITLE
cursor info: display "masked" for masked pixels, rather than "0"

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#19]
For a frame containing masked pixels, cursor info should display those masked pixels as "masked", rather than 0 or some other numbers (e.g. -1.02).

**Comment by veggiesaurus** [comment]
How do we know which pixels are masked? Are masked pixels not NaNs?

**Comment by kswang1029** [comment]
with a conversation with Mark, NaN pixels are replaced by the minimum value of the frame so that the image data can be compressed with ZFP (correct me if I mis-understand it).

I would suggest in the backend, we still replace the NaN value by some other floating number but a unique value so that in the frontend when a cursor points it, we intend display that unique value by "masked". Is this doable?

**Comment by veggiesaurus** [comment]
Mark hasn't finished the ZFP implementation. The expected behaviour from the backend is as follows: 
1) Run through the data, and generate a run-length-encoded array of NaN values
2) Run through the array, replacing NaNs with a sensible value, based on the surrounding pixels

On the frontend, the run-length-encoded array is used after decompression to replace NaN values. So this is an issue for the carta backend, rather than frontend

**Comment by kswang1029** [comment]
I see. I will talk to Mark about this. Issue closed. :)
